clc; clear; format long;

plots = initializePlots();

linkage = Linkage(plots);
linkage.analyzeStatics()
% linkage.analyzeDynamics()

function plots = initializePlots()
    % Set up figures
    plots = struct('jointPos', {},...
                   'linkAngVel', {},...
                   'linkAngAccel', {}...
                  );
    % 'jointVel', {},...
    % 'jointAccel', {},...
    % 'accel', {},...
    % 'staticForce', {},...
    % 'staticTorque', {},...
    % 'dynamicForce', {},...
    % 'dynamicTorque', {},...
    % plots = struct('jointPos', {},...
    %                'jointVel', {})
    plotNames = fieldnames(plots);
    plots = struct();

    % for i = 1:numel(plotNames)
    %     fieldName = plotNames{i};
    %     figure('Name', fieldName);
    %     plots.(fieldName) = axes;
    %     hold(plots.(fieldName), 'on')
    %     if (fieldName ~= "linkAngAccel")
    %         axis(plots.(fieldName), 'equal')
    %     end
    % end
end
