clc; clear; close all;
format long;

plots = initializePlots();

linkage = Linkage(plots);
% linkage.analyzeStatics()
linkage.analyzeDynamics()
savePlots(plots)

function savePlots(plots)
    fieldNames = fieldnames(plots);
    for i = 1:numel(fieldNames)
        fieldName = fieldNames{i};
        folder = "matlab-plots";
        fileName = fieldName;
        fullFileName = fullfile(folder, fileName);

        saveas(plots.(fieldName), fullFileName, 'png')
    end
end

function plots = initializePlots()
    % crankAngleLabel = "Crank Angle (degrees)";
    crankAngleLabel = "Crank Angle Change (degrees)";
    plotConfig = struct('linJointPos', {["Joint X Coordinate for Single Crank Revolution",...
                                         "Joint Y Coordinate for Single Crank Revolution",...
                                         "Joint Linear Position for Single Crank Revolution",...
                                         [1, 1, 1]]},...
                        'linJointVelX', {[crankAngleLabel,...
                                          "Velocity (m/s)",...
                                          "Joint Linear Velocity in x-Direction vs. Crank Angle Change",...
                                         [30, 1, 1]]},...
                        'linJointVelY', {[crankAngleLabel,...
                                          "Velocity (m/s)",...
                                          "Joint Linear Velocity in y-Direction vs. Crank Angle Change",...
                                         [30, 1, 1]]},...
                        'linJointAccelX', {[crankAngleLabel,...
                                           "Acceleration (m/s^2)",...
                                           "Joint Linear Acceleration in x-Direction vs. Crank Angle Change",...
                                         [8, 1, 1]]},...
                        'linJointAccelY', {[crankAngleLabel,...
                                           "Acceleration (m/s^2)",...
                                           "Joint Linear Acceleration in y-Direction vs. Crank Angle Change",...
                                         [4, 1, 1]]},...
                        'angLinkVel', {[crankAngleLabel,...
                                        "Angular Velocity (rad/s)",...
                                        "Link Angular Velocity vs. Crank Angle Change",...
                                         [30, 1, 1]]},...
                        'angLinkAccel', {[crankAngleLabel,...
                                          "Angular Acceleration (rad/s^2)",...
                                          "Link Angular Acceleration vs. Crank Angle Change",...
                                         [5, 1, 1]]},...
                        'linCOMAccel', {[crankAngleLabel,...
                                        "Acceleration (m/s^2)",...
                                        "Linear COM Acceleration vs. Crank Angle Change",...
                                         [4, 1, 1]]},...
                        'dynamicForcesX', {[crankAngleLabel,...
                                          "Force (N)",...
                                          "Dynamic Force in X-Direction at Link COM vs. Crank Angle Change",...
                                         [4, 1, 1]]},...
                        'dynamicForcesY', {[crankAngleLabel,...
                                          "Force (N)",...
                                          "Dynamic Force in Y-Direction at Link COM vs. Crank Angle Change",...
                                         [4, 1, 1]]},...
                        'dynamicTorque', {[crankAngleLabel,...
                                           "Torque (N\cdot m^2)",...
                                           "Dynamic Torque on Crank vs. Crank Angle Change",...
                                         [1, 1, 1]]}...
                        );
    % 'accel', {},...
    % 'staticForce', {},...
    % 'staticTorque', {},...

    % Set up figures
    plots = struct('linJointPos', {},...
                   'linJointVelX', {},...
                   'linJointVelY', {},...
                   'linJointAccelX', {},...
                   'linJointAccelY', {},...
                   'angLinkVel', {},...
                   'angLinkAccel', {},...
                   'linCOMAccel', {},...
                   'dynamicForcesX', {},...
                   'dynamicForcesY', {}...
                  );
    plotNames = fieldnames(plots);
    plots = struct();

    % Store axes handles to each plot
    for i = 1:numel(plotNames)
        fieldName = plotNames{i};
        figure('Name', fieldName);

        % Get axes handle
        plots.(fieldName) = axes;

        % Hold on
        hold(plots.(fieldName), 'on')

        if (fieldName ~= "angLinkAccel") | (fieldName ~= "angLinkVelX") | (fieldName ~= "angLinkVelY")
            axis(plots.(fieldName), 'equal')
        end
        if (fieldName == "angLinkVelX") | (fieldName == "angLinkVelY") |...
                (fieldName == "linJointVelX") | (fieldName == "linJointVelX")
            axis(plots.(fieldName), 'tight')
        end

        % Labels and title
        xlabel(plots.(fieldName), plotConfig.(fieldName)(1))
        ylabel(plots.(fieldName), plotConfig.(fieldName)(2))
        title(plots.(fieldName), plotConfig.(fieldName)(3))

        % Aspect ratio
        % [plotConfig.(fieldName)(4) plotConfig.(fieldName)(5) plotConfig.(fieldName)(6)]
        daspect(plots.(fieldName), [str2num(plotConfig.(fieldName)(4)) str2num(plotConfig.(fieldName)(5)) str2num(plotConfig.(fieldName)(6))])
        % if (fieldName ~= "linJointPos") | (fieldName ~= "linCOMAccel")
            % daspect(plots.(fieldName), [30, 1, 1])
        % end
    end
end
